project:
  type: website

execute:
  cache: true
  freeze: true

website:
  page-navigation: true
  title: "Cite Tools"
  site-url: "https://bcdavasconcelos.github.io/citetools"
  repo-url: https://github.com/bcdavasconcelos/citetools
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By BCDAV, 2023"

  sidebar:
    logo: "images/greek-ship.png"
    # logo: "images/ulysses.png"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: index.qmd
        text: "Cite Tools"
      - icon: github
        href: https://github.com/bcdavasconcelos/citetools
        text: "Cite Tools GitHub"
      - icon: twitter
        href: https://twitter.com/bcdavasconcelos
        text: "Twitter"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Multiple Bibliographies"
        href: docs/citetools/Multiple-Bibliographies/index.qmd
        contents:
          - text: "Prime Matter"
            href: docs/citetools/Multiple-Bibliographies/1-Prime-Matter.qmd
          - text: "How to set it up"
            href: docs/citetools/Multiple-Bibliographies/2-How-to-set-it-up.qmd
          - text: "Advanced"
            href: docs/citetools/Multiple-Bibliographies/3-Advanced/index.qmd
            contents:
              - text: "Using Multiple Bibliographies in Scrivener"
                href: docs/citetools/Multiple-Bibliographies/3-Advanced/1-Using-Multiple-Bibliographies-in-Scrivener.qmd
      - text: "About"
        href: docs/About/index.qmd
        contents:
          - text: "About Cite Tools"
            href: docs/About/1-About-Cite-Tools.qmd
          - text: "About Quarto"
            href: docs/About/2-About-Quarto.qmd
          - text: "About BCDAV"
            href: docs/About/3-About-BCDAV.qmd
format:
  html:
    theme:
      light: [Zephyr] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [Vapor]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  # - include-code-files.lua
  - quarto


