website:
  sidebar:
    contents:
      - section: "Cite Tools"
        href: index.qmd
        contents:
          - text: "The Basics"
            href: docs/01-basics.qmd
            icon: book              
          - text: "Multiple Bibliographies"
            icon: book
            href: docs/02-multibib.qmd
          - text: "Cite Field"
            href: docs/03-cite-field.qmd
            icon: book
          - text: "Citation Backlinks"
            href: docs/04-citation-backlinks.qmd
            icon: book
      - text: "About"
        href: docs/05-about.qmd
        icon: book
    sort: [title, order]
    logo: "images/greek-ship.png"
    # logo: "images/ulysses.png"
    pinned: true
    align: center
    tools:
      - icon: globe
        href: index.qmd
        text: "Cite Tools"
      - icon: github
        href: https://github.com/bcdavasconcelos/citetools
        text: "Cite Tools GitHub"
      - icon: twitter
        href: https://twitter.com/bcdavasconcelos
        text: "Twitter"
    style: "floating" # docked floating
    search: true
    # background: "#453bcd"
    collapse-level: 2
  page-navigation: true
  title: "Cite Tools"
  site-url: "https://bcdavasconcelos.github.io/citetools"
  repo-url: https://github.com/bcdavasconcelos/citetools
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By BCDAV, 2023"

project:
  type: website

# cache: true
# freeze: auto
editor: visual
format-links: [pdf,docx]




format: # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
  html:
    theme: # Slate e
# Pulse: Rocho (muito bonito) | Spacelab: menos brilhante e mais opaco | Materia: azul claro pouco (material?) | yeti: github like | United: laranja brilhante |
      light: [Pulse] # Cerulean, Cosmo, Flatly, Journal, Litera, Lumen, Lux, Materia, Minty, Morph, Pulse, Sandstone, Simplex, Sketchy, Spacelab, United, Yeti, Zephyr
      dark: [Solar] # Cyborg, Darkly, Quartz, Slate, Solar, Superhero, Vapor
    mainfont: Alegreya
    # mainfont: "Atkinson Hyperlegible"
    header-includes: |
      <style>
        .callout-header {
          background-color: transparent!important;
        }
      </style>
    code-copy: true
    code-overflow: scroll # scroll, wrap, auto
    toc: true
    reference-location: document # `block`, `section`, `margin`, `document`


filters:
  - fontawesome
  - include-files.lua
  - citetools
  # - include-code-files.lua
  # - quarto


# author: Bernardo César Diniz Athayde Vasconcelos
citeproc: false
bibliography_primary: refs/primary.json
bibliography_secondary: refs/secondary.json
verbosity: ERROR
# csl: https://raw.githubusercontent.com/bcdavasconcelos/ABNT-Phi/main/abnt-phi-sc.csl
