project:
  type: website
  output-dir: docs

website:
  title: "Cite Tools"
  page-navigation: true
  site-url: "https://bcdavasconcelos.github.io/citetools"
  repo-url: https://github.com/bcdavasconcelos/citetools
  repo-actions: [edit, issue]
  sidebar:
    logo: "images/greek-ship.png"
    # logo: "images/ulysses.png"
    pinned: true
    search: true
    style: "floating" # docked floating
    collapse-level: 2
    # background: "#453bcd"
    sort: [title, order]
    align: center
    tools:
      - icon: globe
        href: index.qmd
        text: "Cite Tools"
      - icon: github
        href: https://github.com/bcdavasconcelos/citetools
        text: "Cite Tools GitHub"
      - icon: twitter
        href: https://twitter.com/bcdavasconcelos
        text: "Twitter"
    contents:
      - section: "Cite Tools"
        href: index.qmd
        contents:
          - text: "The Basics"
            href: docs_qmd/01-basics.qmd
            icon: book
          - text: "Multiple Bibliographies"
            icon: book
            href: docs_qmd/02-multibib.qmd
          - text: "Cite Field"
            href: docs_qmd/03-cite-field.qmd
            icon: book
          - text: "Citation Backlinks"
            href: docs_qmd/04-citation-backlinks.qmd
            icon: book
      - text: "About"
        href: docs_qmd/05-about.qmd
        icon: book

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: |
      <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" /></a> BCDAV, 2023

cache: true
freeze: auto
# editor: visual
format-links: [pdf,docx]
mainfont: Source Serif Pro
sansfont: Source Sans Pro
monofont: Source Code Pro
format: # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
  html:
    theme: # Slate e
# Pulse: Rocho (muito bonito) | Spacelab: menos brilhante e mais opaco | Materia: azul claro pouco (material?) | yeti: github like | United: laranja brilhante |
      light: [Pulse] # Cerulean, Cosmo, Flatly, Journal, Litera, Lumen, Lux, Materia, Minty, Morph, Pulse, Sandstone, Simplex, Sketchy, Spacelab, United, Yeti, Zephyr
      dark: [Cyborg] # Cyborg, Darkly, Quartz, Slate, Solar,Superhero, Vapor
    # mainfont: "Atkinson Hyperlegible"
    header-includes: |
      <style>
      @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&family=Source+Serif+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap');
        .callout-header {
          background-color: transparent!important;
        }
        .header, h1, h2, h3, h4, h5, h6{
          font-family: Source Sans Pro, sans-serif!important;
          .p {
            font-family: Source Serif Pro, serif!important;
          }
        }
      </style>
    code-copy: true
    code-overflow: scroll # scroll, wrap, auto
    toc: true
    reference-location: document # `block`, `section`, `margin`, `document`

filters:
#   - fontawesome
#   - include-code-files
  - citetools

citeproc: false
bibliography_primary: refs/primary.json
bibliography_secondary: refs/secondary.json
verbosity: ERROR
# csl: https://raw.githubusercontent.com/bcdavasconcelos/ABNT-Phi/main/abnt-phi-sc.csl
citation:
  author: BCDA Vasconcelos
  issued: 2023
quarto-version: ">=1.3.0"
