---
title: Prime Matter
---

First of all, you will need to be able to provide a bibliography file in one of different possible formats. The most common ones are called `BibLaTeX` or `BibTeX`. However, you can also use `CSL-JSON` files, which is *preferable* since the latter *faster* and it is the format used by `Citeproc` internally to represent bibliographies.

There are many ways to provide a bibliography file. The most common ones are:

1. Keeping a bibliography file yourself and updating it manually. (*Viable only it small projects.*)
2. Using a bibliography manager, such as [Zotero](http://www.zotero.org), [JabRef](https://www.jabref.org), [Bookends](https://www.sonnysoftware.com), [Bibdesk](https://bibdesk.sourceforge.io), [Endnote](https://endnote.com); see also [this comparison on Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_reference_management_software). These programs allows you to edit your bibliography and export it in the desired format.
3. Using a shared bibliography on Github or a shared Zotero online library^[Zotero online libraries can be downloaded using `https://api.zotero.org/groups/LibraryIDhere/items?format=bibtex&limit=150`) where `LibraryIDhere` should be replaced by the 7-digit code in the middle of the library URL].

The important detail here is that you need to be able to export your bibliography in one of the formats mentioned above and that you need to be able to create more than one bibliography file. Once you have this, you can proceed to the next step.

::: {.callout-warning}
## refs/primary.bib
Keeping bibliography files inside `/refs` at the project's root folder is not a requirement, but it is good pratice.
:::

::: {.callout-important}
## Cite Tools, not a bibliography manager
This extension is not a bibliography manager. It does not allow you to edit your bibliography. It only allows you to use multiple bibliographies in your document.
:::

