---
title: The Basics of Pandoc Citeproc
bibliography: ../refs/primary.json
citeproc: true
---

Before we can begin with advanced bibliography features in Pandoc and Quarto, we need to get some basics out of the way, as this will be the foundation for the advanced bibliography features.

::: {.callout-tip appearance="simple"}
## Official documentation
See the official documentation on citations at [Pandoc](https://pandoc.org/MANUAL.html#citations) and [Quarto](https://quarto.org/docs/authoring/footnotes-and-citations.html#sec-citations).
:::

::: {.callout-warning collapse="true"}
## Creating a bibliography file
Before you can use Cite Tool, you will need a bibliography file. Although nothing stops you from keeping bibliography files manually, this is not advisable for anything other than very small-scale projects. For everything else, consider using software such as [Zotero](http://www.zotero.org), [JabRef](https://www.jabref.org), [Bookends](https://www.sonnysoftware.com), [Bibdesk](https://bibdesk.sourceforge.io), [Endnote](https://endnote.com) (and see also [this comparison on Wikipedia](https://en.wikipedia.org/wiki/Comparison_of_reference_management_software)). These programs allow you to edit your bibliography and easily export it in the desired format.

The most common format, and one of the oldest, is called `BibTeX` (or `BibLaTeX`); others, more recent, include `CSL-JSON` and `CSL-YAML`. These latter are *preferable* since they perform much faster on **Pandoc** and **Quarto** (being the format used to represent the bibliography internally)^[They are not, however, widely supported, so you'll probably be stuck with `BibTeX` or `BibLaTeX` in some way or other anyway.].

You can also use shared bibliographies on Github (just provide Pandoc with the URL to the raw file) or shared Zotero libraries, which can be downloaded using the API by accessing the link below, where `LibraryID` should be replaced by the 7-digit code in the middle of the library URL.

`https://api.zotero.org/groups/LibraryID/items?format=bibtex&limit=999`
:::


## How to Setup a Simple Bibliography

Set up the bibliography of a document by including the path to the bibliography file in the YAML header.

```yaml
bibliography: path/to/bibfile.bib
csl: path/to/cslfile.csl # optional
```


::: {.callout-warning collapse=true}
## CSL file
If no CSL file is supplied, Pandoc will default to the Chicago Author-Date style. It is advisable to use a CSL file, as it will ensure that the bibliography is formatted according to the style of your choice. You can find a list of available CSL styles in the [Citation Styles Github Repo](https://github.com/citation-style-language/styles) and you can edit them with the [CSL Visual Editor](https://editor.citationstyles.org/visualEditor/) or using [Zotero](https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step).
:::


It is also advisable to keep the bibliography and CSL style files in the default Pandoc folder:

-  {{< fa brands apple >}} macOS: `~/.local/share/pandoc`
 - {{< fa brands linux >}} Linux: `~/.local/share/pandoc`
 - {{< fa brands windows >}} Windows: `C:\Users\USERNAME\AppData\Roaming\pandoc`

You can find the path to your Pandoc folder by running the following command in your terminal:

```bash
pandoc --version
```

This way, you can use the same bibliography and CSL-style files in all your documents. Alternatively, you can keep the files in the same folder as your document, which is the approach favored by [Quarto](https://quarto.org/docs/projects/quarto-projects.html).




::: {.callout-tip collapse=true}
## How to share the Pandoc folder
If the Pandoc folder needs to be shared among multiple devices, you can use a cloud service like Dropbox or Google Drive to store the files and use a `symbolic link` to place the files in the Pandoc folder. For example, if you are using Dropbox, you can run the following command in your terminal:

```bash
ln -s ~/Dropbox/Pandoc ~/.local/share/pandoc
```

The symbolic link will appear as a shortcut pointing to the Dropbox folder and any changes will be reflected in both locations.
:::


If the files are in the default Pandoc folder or the same folder as the document, you can simply supply the file name:

```yaml
bibliography: bibfile.bib
csl: cslfile.csl
```

You can, but you don't have to, place a div at the end of the document or where you want the bibliography to be printed.

```markdown
::: {.references}
:::
```







## How to cite in Pandoc

The vanilla Pandoc and Quarto's Citeproc environment is powerful and its syntax is simple. It uses `@Citekey` for `Author (Date)`and `[-@Citekey]` for `(Date)`.

::: {.callout-tip appearance="simple"}
The advantage of this markup syntax lies in its simplicity and compatibility with all formats supported by Pandoc, a universal document converter.
:::

Here are some examples:

> `@Aubenque1961a` says that... [...] ...on the deliberations of the prudent person `[-@Aubenque1961a]`.

> @Aubenque1961a says that... [...] ...on the deliberations of the prudent person [-@Aubenque1961a].

The citation key is *optionally* followed by a locator, which can be a page number, a line number, a chapter number, or a section number, preceded by a comma.

> ...on the deliberations of the prudent person `[-@Aubenque1961a, p.15]` .

> ...on the deliberations of the prudent person [-@Aubenque1961a, p.15].



##  Syntax Summary


| Syntax | Output |
|----------------|----------------|
| `@Aubenque1961a` | @Aubenque1961a |
| `[@Aubenque1961a]` | [@Aubenque1961a] |
| `[@Aubenque1961a, p.15]` | [@Aubenque1961a, p.15] |
| `[-@Aubenque1961a]` | [-@Aubenque1961a] |
| `[-@Aubenque1961a, p.15]` | [-@Aubenque1961a, p.15] |

: Variations of the Citation syntax


Now that we have the basics covered, let us see what Cite Tools can do for us.
