---
title: Multiple Bibliographies
---


In many areas of research, the ability to split the bibliography into sections is *conditio sine qua non* for publishing. In the humanities, for example, it is common to have a bibliography for primary sources and another for secondary sources. In philosophy, even, they can be very nuanced with sections dedicated to original sources, translations, commentaries, and so on.

::: {.callout-tip collapse="false"}
## Installation

In case you have not done it yet, install the extension using the following command:

```bash
quarto install extension bcdavasconcelos/citetools
```

Or download it at [Github](bcdavasconcelos/citetools).
:::




## How to Setup Multiple Bibliographies


::: {.callout-note collapse="true"}
## `multiple-bibliographies` or `multibib`?
There are two versions of the multilple bibliographies filter by Albert Krewinkel. The first one is called `multiple-bibliographies` and it can be found in the Pandoc Lua Filters [repository](https://github.com/pandoc/lua-filters/tree/master/multiple-bibliographies). The second one is called `multibib` and it can be found in its own [repository](https://github.com/pandoc-ext/multibib). We are using the first one due to a [minute issue](https://github.com/pandoc-ext/multibib/issues/4#issue-1623925814) with he second. The differences between them are boderline inexistent, but there are some.

Both filters are included in the bundle, but only `multiple bibliographies` is being used by default. You are, however, free to experiment with both editing the content of the `_quarto.yaml` file in the `_extension` folder. They have both been [tweaked to work](https://github.com/bcdavasconcelos/citetools/blob/7ac1c6fd8c1d39db56ac5a41c037853cd76ac301/_extensions/citetools/multiple-bibliographies.lua#L66) with the `citetools` extension.
:::


If you are using Quarto, chances are you have a project folder. In this case, add bibliography files to the project folder (it is advisible adding them to a `refs` folder to prevent cluter in the root folder). Then, add the path to the files to the YAML metadata of your document in this way:

```yaml
bibliography_primary: refs/primary.json
bibliography_secondary: refs/secondary.json
```


::: {.callout-warning collapse="true"}
## `multibib`
With `multibib`, you should add all of them to the `bibliography` entry instead, in the form of a dictionary.
```yaml
bibliography:
  primary: refs/primary.json
  secondary: refs/secondary.json
```
::: {.callout-important collapse="true"}
## YAML validation error cause by `multibib`
If you are using `multibib`, which requires a `dictionary` of key-value pairs in the `bibliography` field, Quarto will complain that the content of this field should be a `string` instead. To prevent an error, we should tell it to ignore the YAML validation:

```yaml
validate-yaml: false
```
:::
:::



The path should be relative to the project's root folder. The name of the bibliography should (but doesn't *have to*) be the same as the name of the file, without the extension.

Then, finally, place the bibliographies placeholders in the document where you want the bibliographies to appear.

``` markdown
# Primary Sources

::: {#refs_primary}
:::

# Secondary Sources

::: {#refs_secondary}
:::
```

Each `refs_bib_name` `div` should have a matching entry `bibliography_bib_name` in the metadata. They will be filled with the citations from the respective bibliography files.

::: {.callout-important collapse="false"}
## Div names
if you have a bibliography named `bibliography_primary`, the placeholder **must** be named `refs-primary` or `refs_primary`. That is, the name of the placeholder must match the name of the `bibliography_` entry (without the prefix) *otherwise nothing will print*.


Also, please note that if the placeholder doesn't make its way into the document, the references in that file will not be printed.
:::



## Minimal example with strategy to ensure matching IDs

To make sure ids match, it can be a good strategy placing the bibliography file close to the div placeholder.

```markdown
---
title: Multiple Bibliographies
---

[@EN] [@Aubenque1961a]


## Primary Sources

---
bibliography_primary: refs/primary.json
---

::: {#refs_primary}
:::

## Secondary Sources

---
bibliography_secondary: refs/secondary.json
---

::: {#refs_secondary}
:::
```

You should have a working document with multiple bibliographies:


[@EN] [@Aubenque1961a]

### Primary Sources  {.appendix}
::: {#refs_primary}
:::
### Secondary Sources  {.appendix}
::: {#refs_secondary}
:::
