---
title: How to Setup a Simple Bibliography
---

To set up the bibliography, you need to add the path to [the bibliography file](prime-matter.qmd) to the YAML metadata of your document.

```yaml
bibliography: path/to/bibfile.bib
csl: path/to/cslfile.csl # optional
```


::: {.callout-warning collapse=true}
## CSL file
If no CSL file is supplied, Pandoc will default to the Chicago Author-Date style. It is advisable to use a CSL file, as it will ensure that the bibliography is formatted according to the style of your choice. You can find a list of available CSL styles in the [Citation Styles Github Repo](https://github.com/citation-style-language/styles) and you can edit them with the [CSL Visual Editor](https://editor.citationstyles.org/visualEditor/) or using [Zotero](https://www.zotero.org/support/dev/citation_styles/style_editing_step-by-step).
:::


It is also advisable keeping the bibliography and CSL style files in the default Pandoc folder:

-  {{< fa brands apple >}} macOS: `~/.local/share/pandoc`
 - {{< fa brands linux >}} Linux: `~/.local/share/pandoc`
 - {{< fa brands windows >}} Windows: `C:\Users\USERNAME\AppData\Roaming\pandoc`

You can find the path to your Pandoc folder by running the following command in your terminal:

```bash
pandoc --version
```

::: {.callout-tip collapse=true}
## How to share the Pandoc folder
If the Pandoc folder needs to me shared among multiple devices, you can use a cloud service like Dropbox or Google Drive to store the files and use a `symbolic link` to place the files in the Pandoc folder. For example, if you are using Dropbox, you can run the following command in your terminal:

```bash
ln -s ~/Dropbox/Pandoc ~/.local/share/pandoc
```

The symbolic link will appear as a shortcut pointing to the Dropbox folder and any changes will be reflected in both locations.
:::


This way, you can use the same bibliography and CSL style files in all your documents. Alternatively, you can keep the files in the same folder as your document, which  is the approach favored by [Quarto](https://quarto.org/docs/projects/quarto-projects.html).

If the files are in Pandoc's default folder or in the same folder as the document, you can simply supply the file name:

```yaml
bibliography: bibfile.bib
csl: cslfile.csl
```

You can, but you don't have to, place a div at the end of the document or where you want the bibliography to be printed.

```markdown
::: {.references}
:::
```
